services:
  backend:
    build: ./Dhakiya-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - frontend

  frontend:
    build: ./Dhakiya-frontend
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
